var e = require("./config"), r = e.env, t = (e.syt_rd, e.gdUrl), o = (e.passportRequestUrl, 
e.passportUrlR), i = (e.sytMidUrl, e.buryMidUrl), a = e.passportMidUrl, n = e.trackMidUrl, s = e.trackUrlT, c = (e.trackUrlO, 
e.passportBaseUrl), d = e.wxPayDomain, g = e.serveWxDomain, p = e.serveDomain, l = "", v = "", u = "", y = "", m = "", C = wx.getStorageSync("env");

C && (r = C), console.log("当前的环境是", r);

if ("ip" == r) {
    wx.getStorageSync("customeServiceConfig");
    v = l, m = baseUrlT + i, u = o, y = s;
} else m = l + i, u = l + a, y = l + n;

var f = {
    checkToken: c[r] + "/user/vertify",
    getCode: c[r] + "/mobile/getcode",
    login: c[r] + "/mobile/login",
    getTempToken: c[r] + "/user/getTempTokenByMiniProgram",
    getAnnounceByCity: v + "/announce/getannouncebycity",
    getUnfinishedOrderNum: v + "/order/getunfinishedordernum",
    getOrderlist: v + "/order/getorderlist",
    getOrderDetail: v + "/order/getorderdetail",
    getCostDetail: v + "/order/costdetail",
    getCancelReason: v + "/order/cancelreason",
    saveCancelReason: v + "/order/savecancelreason",
    cancelOrder: v + "/order/cancelorder",
    getSendOrder: v + "/order/sendorder",
    getOrderBaseInfo: v + "/order/orderbaseinfo",
    getDriverGeoPoints: l + "/api/wechat/gps/api/gps/getdrivergeopoints",
    getOrderTrail: v + "/api/gps/getordertrail",
    getWxPay: d[r] + "/api/cashier/wechat/miniProgram/pay",
    postFormId: v + "/pushformids",
    getCarList: v + "/car/getcardetail",
    getCityConfig: v + "/city/getcityconfig",
    getLocationInfo: g[r] + "/api/kuaigou/banjia/config/localcity",
    getUserCouponList: v + "/coupon/getusercouponlist",
    getOrderConpon: v + "/coupon/getordercoupon",
    getOrderDisableCoupon: v + "/coupon/getorderdisablecoupon",
    getBestCoupon: v + "/coupon/getbestcoupon",
    bindCoupon: v + "/coupon/bindcoupon",
    getOpenCity: v + "/city/getopencity",
    getHotCity: v + "/city/gethotcity",
    getPastCity: v + "/user/getpastcity",
    updateUserCity: v + "/user/savepastcity",
    saveConsignee: v + "/user/saveconsignee",
    getConsignee: v + "/user/getconsignee",
    batchEstimatePrice: v + "/trade/batchestimateprice",
    createOrder: v + "/order/createorder",
    getOrderextraService: v + "/order/getorderextraservice",
    getPersonalInfo: v + "/user/getpersonalinfo",
    getHistoryAddress: v + "/user/getpastaddress",
    savePastAddress: v + "/user/savepastaddress",
    getPredictRemark: v + "/order/getpredictremark",
    getUserToolBox: v + "/usertoolbox/getusertoolbox",
    getMoveCarlist: v + "/car/getmovecarlist",
    moveEstimatePrice: v + "/trade/moveestimateprice",
    hasUnfinshMoveOrder: v + "/user/hasunfinshmoveorder",
    createMoveClue: v + "/order/createmoveclue",
    getConfigbyCity: v + "/config/getconfigbycity",
    getFreshConpon: v + "/coupon/newuserbindcoupon",
    initDriver: "/favoritedriver/init",
    addDriver: "/favoritedriver/add",
    removeDriver: "/favoritedriver/remove",
    getNearbyDriver: "/nearbydriver/list",
    getFavoriteDriver: "/favoritedriver/list",
    getChooseDriverList: "/order/broadcast/choosedriverlist",
    chooseDriver: "/user/choosedriver",
    getBroadingOrder: "/order/broadcast/inprogress",
    getChooseDriver: "/order/broadcast/choosedriverlist",
    getCarDetail: "/order/detail",
    getCarUserCancel: "/order/usercancel",
    getCarTypeList: "/favoritedriver/availablecartypelist",
    getCarLocate: "/localInfo/locate",
    radioCreateOrder: "/order/createbroadcastorder",
    privateCreaterOrder: "/order/createrOrder",
    getCarPrice: "/order/price/estimate",
    getDriverInfo: "/user/getdriverinfo",
    getCarOrderList: "/order/monthlist",
    getInviterInfo: "/activity/invite/inviterinfo",
    getDiscountByCity: "/activity/invite/cityred",
    getVirtualPhone: "/fictitiousphone/get",
    getOpenId: p[r] + "/config/getopenid",
    postLog: m + "/s.png",
    getShareInfo: v + "/share/redbag",
    getLocationByKeyword: t + "/place/text",
    reInviteDriver: "/favoritedriver/invitedriver",
    getWebsocketUrl: "/mc/webaddr",
    postBuryPoint: y + "/applet/log/sy",
    scanCodeBindCoupon: "".concat("", "/activity/common/bindCoupon"),
    getOpenIdBindUser: "".concat("", "/activity/wechat/getOpenIdBindUser"),
    getTemplateDetail: "".concat("", "/activity/common/templateDetail"),
    getPayPaySign: "".concat("", "/activity/common/templateDetail")
}, b = "".concat(c[r], "/v2/common/tempTokenBridge");

module.exports = {
    DOMAIN: v,
    PASSPORT_DOMAIN: u,
    WEBSOCKET_DOMAIN: "",
    TRACK_DOMAIN: y,
    API: f,
    PASSPORT_MID_URL: b
};